#### Indexing and Slicing

In [1]:
import numpy as np

In [2]:
a1=np.arange(1,10)
a2=np.random.random((3,4))*100

In [3]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Negative Indexing:
a1[-1]

np.int64(9)

In [5]:
#Slicing in 1D array:
a1[2:6]

array([3, 4, 5, 6])

In [6]:
a2

array([[32.82865256, 74.78526917, 29.54412267, 12.77169571],
       [97.08346244, 17.25642088,  8.07576359, 21.60393152],
       [50.59322959, 29.9611691 , 32.4073577 , 32.04046582]])

In [7]:
a2[2,1] #(Row,Column)

np.float64(29.961169103430773)

In [8]:
a2[1:,1:3]

array([[17.25642088,  8.07576359],
       [29.9611691 , 32.4073577 ]])

In [9]:
a2[::2,::3]

array([[32.82865256, 12.77169571],
       [50.59322959, 32.04046582]])

In [10]:
a2[1,::3]

array([97.08346244, 21.60393152])

In [11]:
a2[0:2,2:]

array([[29.54412267, 12.77169571],
       [ 8.07576359, 21.60393152]])

In [12]:
a3=np.arange(1,28).reshape(3,3,3)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
a3[1,1,1] #(Which 2D array,row,columns)

np.int64(14)

In [15]:
a3[2]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [16]:
a3[0,1,:]

array([4, 5, 6])

In [17]:
a3[::2,::3,::2]

array([[[ 1,  3]],

       [[19, 21]]])

In [18]:
a4=np.arange(8).reshape(4,2)
a5=np.arange(12,20).reshape(4,2)

In [19]:
a4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [21]:
a6=np.hstack((a4,a5))
a6

array([[ 0,  1, 12, 13],
       [ 2,  3, 14, 15],
       [ 4,  5, 16, 17],
       [ 6,  7, 18, 19]])

In [22]:
np.hsplit(a6,4)

[array([[0],
        [2],
        [4],
        [6]]),
 array([[1],
        [3],
        [5],
        [7]]),
 array([[12],
        [14],
        [16],
        [18]]),
 array([[13],
        [15],
        [17],
        [19]])]