#### Indexing and Slicing

In [1]:
import numpy as np

In [2]:
a1=np.arange(1,10)
a2=np.random.random((3,4))*100

In [3]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Negative Indexing:
a1[-1]

np.int64(9)

In [5]:
#Slicing in 1D array:
a1[2:6]

array([3, 4, 5, 6])

In [6]:
a2

array([[92.21201338,  4.56822235, 84.14363933, 89.59700603],
       [51.7984262 ,  3.75426434, 32.47905053, 39.53750123],
       [12.20206715, 14.78522675, 85.93525909,  3.55326198]])

In [7]:
a2[2,1] #(Row,Column)

np.float64(14.785226752521085)

In [8]:
a2[1:,1:3]

array([[ 3.75426434, 32.47905053],
       [14.78522675, 85.93525909]])

In [9]:
a2[::2,::3]

array([[92.21201338, 89.59700603],
       [12.20206715,  3.55326198]])

In [10]:
a2[1,::3]

array([51.7984262 , 39.53750123])

In [11]:
a2[0:2,2:]

array([[84.14363933, 89.59700603],
       [32.47905053, 39.53750123]])

In [12]:
a3=np.arange(1,28).reshape(3,3,3)

In [13]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
a3[1,1,1] #(Which 2D array,row,columns)

np.int64(14)

In [15]:
a3[2]

array([[19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [16]:
a3[0,1,:]

array([4, 5, 6])

In [17]:
a3[::2,::3,::2]

array([[[ 1,  3]],

       [[19, 21]]])

In [18]:
a4=np.arange(8).reshape(4,2)
a5=np.arange(12,20).reshape(4,2)

In [19]:
a4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
a5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [21]:
a6=np.hstack((a4,a5))
a6

array([[ 0,  1, 12, 13],
       [ 2,  3, 14, 15],
       [ 4,  5, 16, 17],
       [ 6,  7, 18, 19]])

In [22]:
np.hsplit(a6,4)

[array([[0],
        [2],
        [4],
        [6]]),
 array([[1],
        [3],
        [5],
        [7]]),
 array([[12],
        [14],
        [16],
        [18]]),
 array([[13],
        [15],
        [17],
        [19]])]

##### Fancy Indexing

In [23]:
a7=np.arange(18).reshape(3,6)
a7

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [24]:
a7[[0,1]] # Just past the index inside the list

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
a7[:,[3,4]]

array([[ 3,  4],
       [ 9, 10],
       [15, 16]])

##### Boolean Indexing

In [26]:
a8=np.random.randint(1,100,24).reshape(6,4)
a8

array([[92, 10, 30, 67],
       [84, 13, 95, 75],
       [ 9, 79, 48, 90],
       [37, 45, 31, 35],
       [61, 16, 72, 79],
       [35, 94, 51, 70]], dtype=int32)

In [27]:
#Find all numbers greater than 50:
a8[a8>50]

array([92, 67, 84, 95, 75, 79, 90, 61, 72, 79, 94, 51, 70], dtype=int32)

In [28]:
#Find all numbers greater than 50 and are even:
a8[(a8>50) & (a8%2==0)]

array([92, 84, 90, 72, 94, 70], dtype=int32)

In [29]:
#Find all the numbers not divisble by 7:
a8[~(a8%7==0)]

array([92, 10, 30, 67, 13, 95, 75,  9, 79, 48, 90, 37, 45, 31, 61, 16, 72,
       79, 94, 51], dtype=int32)