### Different Ways to create NumPy Arrays:

In [1]:
import numpy as np

a=np.array([1,2,3]) # 1D
b=np.array([[1,2,3],[4,5,6]]) # 2D
print(a)
print("-"*50)
print(b)

[1 2 3]
--------------------------------------------------
[[1 2 3]
 [4 5 6]]


In [2]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [3]:
np.arange(1,9).reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.zeros((1,4))

array([[0., 0., 0., 0.]])

In [6]:
np.random.random((3,4))*10

array([[7.86057262, 9.52657644, 1.16292002, 7.32937108],
       [7.14221689, 5.87544024, 1.37360695, 1.59658178],
       [8.05692013, 9.68189088, 3.63048832, 9.93671343]])

In [7]:
np.linspace(-20,20,10)

array([-20.        , -15.55555556, -11.11111111,  -6.66666667,
        -2.22222222,   2.22222222,   6.66666667,  11.11111111,
        15.55555556,  20.        ])

In [8]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])