### Numpy Function:

In [1]:
import numpy as np

In [2]:
a1=np.round(np.random.random((3,3))*100)
a2=np.arange(1,10).reshape(3,3)

In [3]:
a1

array([[63., 61., 85.],
       [84.,  3.,  2.],
       [32., 77., 20.]])

In [4]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.max(a1)

np.float64(85.0)

In [6]:
np.min(a1,axis=1)

array([61.,  2., 20.])

In [7]:
np.mean(a1)

np.float64(47.44444444444444)

In [8]:
np.std(a1)

np.float64(31.759901731974725)

In [9]:
np.dot(a1,a2)

array([[ 902., 1111., 1320.],
       [ 110.,  199.,  288.],
       [ 480.,  609.,  738.]])